# Generated by Django 5.2.18 on 2026-10-09 03:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=500)),
                ("doc_type", models.CharField(max_length=64)),
                ("namespace", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("revision_date", models.DateField()),
                ("effective_date", models.DateField()),
                ("metadata", models.JSONField()),
                ("source_filename", models.CharField(max_length=255)),
                (
                    "ingested_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ("document_id", "revision"),
            },
        ),
        migrations.CreateModel(
            name="DocumentNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_id", models.CharField(max_length=128)),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("chapter", "Chapter"),
                            ("section", "Section"),
                            ("topic", "Topic"),
                        ],
                        max_length=16,
                    ),
                ),
                ("number", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=500)),
                ("sequence", models.PositiveIntegerField()),
                ("position", models.PositiveIntegerField()),
                ("content_blocks", models.JSONField(blank=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="documents.documentnode",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="documents.documentversion",
                    ),
                ),
            ],
            options={
                "ordering": ("version_id", "position"),
            },
        ),
        migrations.AddConstraint(
            model_name="documentversion",
            constraint=models.UniqueConstraint(
                fields=("document", "revision"), name="unique_document_revision"
            ),
        ),
        migrations.AddIndex(
            model_name="documentnode",
            index=models.Index(
                fields=["version", "parent", "sequence"],
                name="node_parent_sequence_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentnode",
            index=models.Index(
                fields=["version", "position"], name="node_position_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentnode",
            constraint=models.UniqueConstraint(
                fields=("version", "node_id"), name="unique_version_node_id"
            ),
        ),
    ]
