# Generated by Django 5.2.18 on 2026-10-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="documentnode",
            constraint=models.UniqueConstraint(
                fields=("version", "position"), name="unique_version_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentnode",
            constraint=models.UniqueConstraint(
                fields=("version", "parent", "sequence"),
                name="unique_version_parent_sequence",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentnode",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("node_type", "chapter"), ("parent__isnull", True)),
                    models.Q(("node_type", "section"), ("parent__isnull", False)),
                    models.Q(("node_type", "topic"), ("parent__isnull", False)),
                    _connector="OR",
                ),
                name="documentnode_valid_parent_reference",
            ),
        ),
    ]
