# Generated by Django 5.2.18 on 2026-10-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_documentnode_unique_version_position_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="documentnode",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("version", "sequence"),
                name="unique_version_root_sequence",
            ),
        ),
    ]
