# Generated by Django 5.2.18 on 2026-10-10 01:24

import django.db.models.deletion
from django.db import migrations, models


def backfill_content_anchors(apps, schema_editor):
    """Create anchors for revisions that were ingested before this table existed.

    Each topic already stores its blocks, so the anchors are rebuilt from those
    rows one revision at a time. With no stored revisions this does nothing.

    A revision in which a block or check ID repeats, or equals a chapter,
    section or topic ID, would make that ID ambiguous. The migration stops
    there instead of guessing which target the ID means.
    """
    DocumentVersion = apps.get_model("documents", "DocumentVersion")
    DocumentNode = apps.get_model("documents", "DocumentNode")
    ContentAnchor = apps.get_model("documents", "ContentAnchor")
    database = schema_editor.connection.alias

    versions = list(
        DocumentVersion.objects.using(database)
        .order_by("id")
        .values_list("id", "document_id", "revision")
    )
    for version_id, document_id, revision in versions:
        nodes = list(
            DocumentNode.objects.using(database)
            .filter(version_id=version_id)
            .order_by("position")
            .values_list("id", "node_id", "node_type", "content_blocks")
        )
        anchors = []
        for topic_id, _, node_type, blocks in nodes:
            if node_type != "topic":
                continue
            for block in blocks or []:
                anchors.append(
                    ContentAnchor(
                        version_id=version_id,
                        topic_id=topic_id,
                        anchor_id=block["id"],
                        anchor_type=block["type"],
                    )
                )
                if block["type"] != "checklist":
                    continue
                for check in block["checks"]:
                    anchors.append(
                        ContentAnchor(
                            version_id=version_id,
                            topic_id=topic_id,
                            anchor_id=check["id"],
                            anchor_type="check",
                        )
                    )

        seen = {node_id for _, node_id, _, _ in nodes}
        repeated = set()
        for anchor in anchors:
            if anchor.anchor_id in seen:
                repeated.add(anchor.anchor_id)
            seen.add(anchor.anchor_id)
        if repeated:
            raise RuntimeError(
                f"Cannot build content anchors for {document_id} revision "
                f"{revision}: IDs used more than once in that revision: "
                f"{', '.join(sorted(repeated)[:5])}. Repair or remove that "
                "revision, then run this migration again."
            )
        if anchors:
            ContentAnchor.objects.using(database).bulk_create(anchors)


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_documentnode_unique_version_root_sequence"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentAnchor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anchor_id", models.CharField(max_length=128)),
                (
                    "anchor_type",
                    models.CharField(
                        choices=[
                            ("para", "Para"),
                            ("note", "Note"),
                            ("caution", "Caution"),
                            ("warning", "Warning"),
                            ("list", "List"),
                            ("table", "Table"),
                            ("checklist", "Checklist"),
                            ("check", "Check"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anchors",
                        to="documents.documentnode",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anchors",
                        to="documents.documentversion",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("version", "anchor_id"), name="unique_version_anchor_id"
                    )
                ],
            },
        ),
        migrations.RunPython(
            backfill_content_anchors,
            migrations.RunPython.noop,
        ),
    ]
